/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Enable2FAScreen` | `/Enable2FAScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LandingScreen` | `/LandingScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapScreen` | `/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ReportScreen` | `/ReportScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/MapScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Enable2FAScreen` | `/Enable2FAScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LandingScreen` | `/LandingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MapScreen` | `/MapScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ReportScreen` | `/ReportScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/MapScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Enable2FAScreen${`?${string}` | `#${string}` | ''}` | `/Enable2FAScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LandingScreen${`?${string}` | `#${string}` | ''}` | `/LandingScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LoginScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MapScreen${`?${string}` | `#${string}` | ''}` | `/MapScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ReportScreen${`?${string}` | `#${string}` | ''}` | `/ReportScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Enable2FAScreen` | `/Enable2FAScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LandingScreen` | `/LandingScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapScreen` | `/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ReportScreen` | `/ReportScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
